# Translations template for PROJECT.
# Copyright (C) 2016 ORGANIZATION
# This file is distributed under the same license as the PROJECT project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2016.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PROJECT VERSION\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2016-04-17 06:10+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.2.0\n"

#: trove/backup/models.py:97
#, python-format
msgid "Unable to create backup record for instance: %s"
msgstr ""

#: trove/backup/models.py:260
#, python-format
msgid "Backup %s cannot be deleted because it is running."
msgstr ""

#: trove/backup/models.py:310
#, python-format
msgid "Bad location for backup object: %s"
msgstr ""

#: trove/backup/service.py:60
#, python-format
msgid "Creating a backup for tenant %s"
msgstr ""

#: trove/backup/service.py:76
#, python-format
msgid "Deleting backup for tenant %(tenant_id)s ID: %(backup_id)s"
msgstr ""

#: trove/cluster/models.py:132
#, python-format
msgid "Setting task to NONE on cluster %s"
msgstr ""

#: trove/cluster/models.py:211
#: trove/common/strategies/cluster/experimental/mongodb/api.py:242
#: trove/common/strategies/cluster/experimental/mongodb/api.py:448
#, python-format
msgid ""
"This action cannot be performed on the cluster while the current cluster "
"task is '%s'."
msgstr ""

#: trove/cluster/models.py:254
#, python-format
msgid "Action %s not supported"
msgstr ""

#: trove/cluster/models.py:257
msgid "Action 'grow' not supported"
msgstr ""

#: trove/cluster/models.py:260
msgid "Action 'shrink' not supported"
msgstr ""

#: trove/cluster/service.py:60 trove/extensions/mgmt/clusters/service.py:77
#: trove/extensions/mgmt/configuration/service.py:81
#: trove/extensions/mgmt/configuration/service.py:108
#: trove/extensions/mgmt/host/instance/service.py:37
#: trove/extensions/mgmt/host/instance/service.py:55
#: trove/extensions/mgmt/instances/service.py:100
#: trove/extensions/mgmt/instances/service.py:123
#: trove/extensions/mgmt/quota/service.py:49 trove/instance/service.py:79
msgid "Invalid request body."
msgstr ""

#: trove/cluster/service.py:62
msgid "Action request should have exactly one action specified in body"
msgstr ""

#: trove/cmd/manage.py:225
#, python-format
msgid "Possible wrong number of arguments supplied %s."
msgstr ""

#: trove/cmd/manage.py:228
msgid "Command failed, please check log for more info."
msgstr ""

#: trove/common/auth.py:65
#, python-format
msgid "Authorized tenant '%(tenant_id)s' request: %(request)s"
msgstr ""

#: trove/common/auth.py:70
#, python-format
msgid "User with tenant id %s cannot access this resource."
msgstr ""

#: trove/common/base_exception.py:103
msgid "Uncaught exception"
msgstr ""

#: trove/common/base_wsgi.py:111
#, python-format
msgid "Could not bind to %(host)s:%(port)s after trying for 30 seconds"
msgstr ""

#: trove/common/base_wsgi.py:372
msgid "Unsupported Content-Type"
msgstr ""

#: trove/common/base_wsgi.py:375
msgid "Malformed request body"
msgstr ""

#: trove/common/base_wsgi.py:727
msgid "cannot understand JSON"
msgstr ""

#: trove/common/base_wsgi.py:751
msgid "cannot understand XML"
msgstr ""

#: trove/common/debug_utils.py:99
msgid ""
"Enabling debugging with eventlet monkey patched produce unexpected "
"behavior."
msgstr ""

#: trove/common/debug_utils.py:120
#, python-format
msgid ""
"Can't connect to remote debug server. Continuing to work in standard "
"mode. Error: %s."
msgstr ""

#: trove/common/exception.py:56
#, python-format
msgid "Failed to save %(model_name)s because: %(error)s."
msgstr ""

#: trove/common/exception.py:61
msgid "Invalid RPC Connection Reuse."
msgstr ""

#: trove/common/exception.py:66 trove/common/exception.py:81
#, python-format
msgid "Resource %(uuid)s cannot be found."
msgstr ""

#: trove/common/exception.py:71
#, python-format
msgid "Capability '%(capability)s' cannot be found."
msgstr ""

#: trove/common/exception.py:76
#, python-format
msgid "Capability '%(capability)s' is disabled."
msgstr ""

#: trove/common/exception.py:86
#, python-format
msgid "User %(uuid)s cannot be found on the instance."
msgstr ""

#: trove/common/exception.py:91
#, python-format
msgid "Database %(uuid)s cannot be found on the instance."
msgstr ""

#: trove/common/exception.py:96
#, python-format
msgid "Cannot find compute instance %(server_id)s for instance %(instance_id)s."
msgstr ""

#: trove/common/exception.py:99
#, python-format
msgid "Resource %(instance_id)s can not be retrieved."
msgstr ""

#: trove/common/exception.py:104
#, python-format
msgid "DnsRecord with name= %(name)s not found."
msgstr ""

#: trove/common/exception.py:109
#, python-format
msgid "Datastore '%(datastore)s' cannot be found."
msgstr ""

#: trove/common/exception.py:114
#, python-format
msgid "Datastore version '%(version)s' cannot be found."
msgstr ""

#: trove/common/exception.py:119
msgid "Datastores cannot be found."
msgstr ""

#: trove/common/exception.py:124
#, python-format
msgid ""
"Flavor %(flavor_id)s is not supported for datastore %(datastore)s version"
" %(datastore_version)s"
msgstr ""

#: trove/common/exception.py:130
#, python-format
msgid ""
"Flavor %(flavor_id)s is already associated with datastore %(datastore)s "
"version %(datastore_version)s"
msgstr ""

#: trove/common/exception.py:136
#, python-format
msgid "Datastore '%(datastore)s' has no version '%(version)s'."
msgstr ""

#: trove/common/exception.py:141
#, python-format
msgid "Datastore version '%(version)s' is not active."
msgstr ""

#: trove/common/exception.py:146
msgid "Please specify datastore. Default datastore cannot be found."
msgstr ""

#: trove/common/exception.py:152
#, python-format
msgid "Default version for datastore '%(datastore)s' not found."
msgstr ""

#: trove/common/exception.py:157
#, python-format
msgid "Datastore manager %(datastore_manager)s cannot be found."
msgstr ""

#: trove/common/exception.py:162
#, python-format
msgid ""
"The '%(operation)s' operation is not supported for the '%(datastore)s' "
"datastore."
msgstr ""

#: trove/common/exception.py:168
#, python-format
msgid "Multiple matches found for '%(name)s', use an UUID to be more specific."
msgstr ""

#: trove/common/exception.py:174
msgid "The server rejected the request due to its size or rate."
msgstr ""

#: trove/common/exception.py:180
#, python-format
msgid "Quota exceeded for resources: %(overs)s."
msgstr ""

#: trove/common/exception.py:185
msgid "Instance volume quota exceeded."
msgstr ""

#: trove/common/exception.py:190
#, python-format
msgid "An error occurred communicating with the guest: %(original_message)s."
msgstr ""

#: trove/common/exception.py:196
msgid "Timeout trying to connect to the Guest Agent."
msgstr ""

#: trove/common/exception.py:201
msgid ""
"The server could not comply with the request since it is either malformed"
" or otherwise incorrect."
msgstr ""

#: trove/common/exception.py:207
#, python-format
msgid "Required element/key - %(key)s was not specified."
msgstr ""

#: trove/common/exception.py:212
#, python-format
msgid "A database with the name \"%(name)s\" already exists."
msgstr ""

#: trove/common/exception.py:217
#, python-format
msgid "A user with the name \"%(name)s\" already exists."
msgstr ""

#: trove/common/exception.py:222
msgid ""
"A configuration group cannot be deleted if it is associated with one or "
"more non-terminated instances. Detach the configuration group from all "
"non-terminated instances and please try again."
msgstr ""

#: trove/common/exception.py:230
msgid "Unable to process the contained request."
msgstr ""

#: trove/common/exception.py:235
msgid "Unauthorized request."
msgstr ""

#: trove/common/exception.py:240
msgid "No change was requested in the size of the instance."
msgstr ""

#: trove/common/exception.py:245
#, python-format
msgid "Cannot find the volumes attached to compute instance %(server_id)s."
msgstr ""

#: trove/common/exception.py:251
msgid "Failed to create a volume in Nova."
msgstr ""

#: trove/common/exception.py:256
msgid "Volume size was not specified."
msgstr ""

#: trove/common/exception.py:261
#, python-format
msgid "Local storage not specified in flavor ID: %(flavor)s."
msgstr ""

#: trove/common/exception.py:266
msgid "Local storage support is not enabled."
msgstr ""

#: trove/common/exception.py:271
msgid "Volume support is not enabled."
msgstr ""

#: trove/common/exception.py:276
#, python-format
msgid "Replication is not supported for the '%(datastore)s' datastore."
msgstr ""

#: trove/common/exception.py:282
msgid "Exception encountered attaching slave to new replica source."
msgstr ""

#: trove/common/exception.py:287
#, python-format
msgid ""
"An error occurred communicating with the task manager: "
"%(original_message)s."
msgstr ""

#: trove/common/exception.py:293
#, python-format
msgid "Value could not be converted: %(msg)s."
msgstr ""

#: trove/common/exception.py:298
msgid "Polling request timed out."
msgstr ""

#: trove/common/exception.py:303
msgid "User does not have admin privileges."
msgstr ""

#: trove/common/exception.py:308
#, python-format
msgid "The following values are invalid: %(errors)s."
msgstr ""

#: trove/common/exception.py:313
msgid "Not Found."
msgstr ""

#: trove/common/exception.py:318
msgid "Failed to update instances."
msgstr ""

#: trove/common/exception.py:323
msgid "Config file not found."
msgstr ""

#: trove/common/exception.py:328
msgid "Paste app not found."
msgstr ""

#: trove/common/exception.py:332
msgid "Quota could not be found."
msgstr ""

#: trove/common/exception.py:336
#, python-format
msgid "Quota for tenant %(tenant_id)s could not be found."
msgstr ""

#: trove/common/exception.py:340
#, python-format
msgid "Unknown quota resources %(unknown)s."
msgstr ""

#: trove/common/exception.py:344
msgid "Unable to upload Backup to swift."
msgstr ""

#: trove/common/exception.py:348
msgid "Unable to download Backup from swift"
msgstr ""

#: trove/common/exception.py:352
msgid "Unable to create Backup."
msgstr ""

#: trove/common/exception.py:356
msgid "Unable to update Backup table in database."
msgstr ""

#: trove/common/exception.py:361 trove/extensions/security_group/models.py:60
msgid "Failed to create Security Group."
msgstr ""

#: trove/common/exception.py:366
msgid "Failed to delete Security Group."
msgstr ""

#: trove/common/exception.py:371
msgid "Failed to create Security Group Rule."
msgstr ""

#: trove/common/exception.py:376
msgid "Failed to delete Security Group Rule."
msgstr ""

#: trove/common/exception.py:381
#, python-format
msgid ""
"Error creating security group rules. Malformed port(s). Port must be an "
"integer. FromPort = %(from)s greater than ToPort = %(to)s."
msgstr ""

#: trove/common/exception.py:388
#, python-format
msgid ""
"Unable to create instance because backup %(backup_id)s is not completed. "
"Actual state: %(state)s."
msgstr ""

#: trove/common/exception.py:393
#, python-format
msgid "Backup file in %(location)s was not found in the object storage."
msgstr ""

#: trove/common/exception.py:398
#, python-format
msgid ""
"The datastore from which the backup was taken, %(datastore1)s, does not "
"match the destination datastore of %(datastore2)s."
msgstr ""

#: trove/common/exception.py:404
#, python-format
msgid "Swift account not accessible for tenant %(tenant_id)s."
msgstr ""

#: trove/common/exception.py:408
#, python-format
msgid "Swift is disabled for tenant %(tenant_id)s."
msgstr ""

#: trove/common/exception.py:412
#, python-format
msgid ""
"The request indicates that user %(user)s should have access to database "
"%(database)s, but database %(database)s is not included in the initial "
"databases list."
msgstr ""

#: trove/common/exception.py:418
msgid ""
"Two or more databases share the same name in the initial databases list. "
"Please correct the names or remove the duplicate entries."
msgstr ""

#: trove/common/exception.py:424
msgid ""
"Two or more users share the same name and host in the initial users list."
" Please correct the names or remove the duplicate entries."
msgstr ""

#: trove/common/exception.py:430
#, python-format
msgid ""
"Current Swift object checksum does not match original checksum for backup"
" %(backup_id)s."
msgstr ""

#: trove/common/exception.py:435
#, python-format
msgid "%(key)s is not a supported configuration parameter."
msgstr ""

#: trove/common/exception.py:439
#, python-format
msgid "No configuration parser found for datastore %(datastore_manager)s."
msgstr ""

#: trove/common/exception.py:444
#, python-format
msgid ""
"Datastore Version on Configuration %(config_datastore_version)s does not "
"match the Datastore Version on the instance "
"%(instance_datastore_version)s."
msgstr ""

#: trove/common/exception.py:451
#, python-format
msgid ""
"%(parameter_name)s parameter can no longer be set as of "
"%(parameter_deleted_at)s."
msgstr ""

#: trove/common/exception.py:456
#, python-format
msgid ""
"%(parameter_name)s parameter already exists for datastore version "
"%(datastore_version)s."
msgstr ""

#: trove/common/exception.py:461
#, python-format
msgid ""
"Instance %(instance_id)s already has a Configuration Group attached: "
"%(configuration_id)s."
msgstr ""

#: trove/common/exception.py:466
#, python-format
msgid ""
"The operation you have requested cannot be executed because the instance "
"status is currently: %(status)s."
msgstr ""

#: trove/common/exception.py:472
#, python-format
msgid ""
"Endpoint not found for service_type=%(service_type)s, "
"endpoint_type=%(endpoint_type)s, endpoint_region=%(endpoint_region)s."
msgstr ""

#: trove/common/exception.py:479
msgid "Empty catalog."
msgstr ""

#: trove/common/exception.py:483
#, python-format
msgid ""
"Instance with replication strategy %(guest_strategy)s cannot replicate "
"from instance with replication strategy %(replication_strategy)s."
msgstr ""

#: trove/common/exception.py:489
#, python-format
msgid ""
"The target instance has only %(slave_volume_size)sG free, but the "
"replication snapshot contains %(dataset_size)sG of data."
msgstr ""

#: trove/common/exception.py:495
msgid "The replica source cannot be deleted without detaching the replicas."
msgstr ""

#: trove/common/exception.py:500
#, python-format
msgid "Module type '%(module_type)s' was not found."
msgstr ""

#: trove/common/exception.py:505
msgid ""
"A module cannot be deleted or its contents modified if it has been "
"applied to a non-terminated instance, unless the module has been marked "
"as 'live_update.' Please remove the module from all non-terminated "
"instances and try again."
msgstr ""

#: trove/common/exception.py:514
#, python-format
msgid ""
"A module with the name '%(name)s' already exists for datastore "
"'%(datastore)s' and datastore version '%(ds_version)s'"
msgstr ""

#: trove/common/exception.py:521
#, python-format
msgid "You must be admin to %(action)s a module with these options. %(options)s"
msgstr ""

#: trove/common/exception.py:526
#, python-format
msgid "Cluster '%(cluster)s' cannot be found."
msgstr ""

#: trove/common/exception.py:530
msgid "The flavor for each instance in a cluster must be the same."
msgstr ""

#: trove/common/exception.py:534
msgid "The network for each instance in a cluster must be the same."
msgstr ""

#: trove/common/exception.py:538
#, python-format
msgid "Network Resource %(uuid)s cannot be found."
msgstr ""

#: trove/common/exception.py:542
msgid "A volume size is required for each instance in the cluster."
msgstr ""

#: trove/common/exception.py:546
msgid "The volume size for each instance in a cluster must be the same."
msgstr ""

#: trove/common/exception.py:551
#, python-format
msgid ""
"The number of instances for your initial cluster must be "
"%(num_instances)s."
msgstr ""

#: trove/common/exception.py:556
#, python-format
msgid ""
"The number of instances for your initial cluster must be at least "
"%(num_instances)s."
msgstr ""

#: trove/common/exception.py:561
msgid ""
"The number of instances in your cluster cannot safely be lowered below "
"the current level basedon your current fault-tolerance settings."
msgstr ""

#: trove/common/exception.py:567
msgid "Must leave at least one instance in the cluster when shrinking."
msgstr ""

#: trove/common/exception.py:572
#, python-format
msgid ""
"Instance(s) %(id)s currently in use and cannot be deleted. Details: "
"%(reason)s"
msgstr ""

#: trove/common/exception.py:577
msgid "Operation not supported for instances that are part of a cluster."
msgstr ""

#: trove/common/exception.py:583
#, python-format
msgid "The '%(operation)s' operation is not supported for cluster."
msgstr ""

#: trove/common/exception.py:587
#, python-format
msgid "Operation not allowed for tenant %(tenant_id)s."
msgstr ""

#: trove/common/exception.py:591
#, python-format
msgid "Clusters not supported for %(datastore)s-%(datastore_version)s."
msgstr ""

#: trove/common/exception.py:596
#, python-format
msgid ""
"Backup is too large for given flavor or volume. Backup size: "
"%(backup_size)s GBs. Available size: %(disk_size)s GBs."
msgstr ""

#: trove/common/exception.py:603
#, python-format
msgid "Image %(uuid)s cannot be found."
msgstr ""

#: trove/common/exception.py:608
#, python-format
msgid "A datastore version with the name '%(name)s' already exists."
msgstr ""

#: trove/common/extensions.py:203
#, python-format
msgid "Extension with alias %s does not exist"
msgstr ""

#: trove/common/extensions.py:401
#, python-format
msgid "Exception loading extension: %s"
msgstr ""

#: trove/common/limits.py:88
#, python-format
msgid ""
"Only %(value)s %(verb)s request(s) can be made to %(uri)s every "
"%(unit_string)s."
msgstr ""

#: trove/common/limits.py:212
msgid "This request was rate-limited."
msgstr ""

#: trove/common/notification.py:356
#, python-format
msgid "Notification %s must include 'request' property"
msgstr ""

#: trove/common/notification.py:368
#, python-format
msgid ""
"The following required keys not defined for notification %(name)s: "
"%(keys)s"
msgstr ""

#: trove/common/notification.py:373
#, python-format
msgid "Notification %s must include a 'server_type' for correct routing"
msgstr ""

#: trove/common/template.py:138
#, python-format
msgid "Missing heat template for %(s_datastore_manager)s."
msgstr ""

#: trove/common/utils.py:243
#, python-format
msgid ""
"Command '%(cmd)s' failed. %(description)s Exit code: %(exit_code)s\n"
"stderr: %(stderr)s\n"
"stdout: %(stdout)s"
msgstr ""

#: trove/common/utils.py:252
msgid "Got a timeout but not the one expected."
msgstr ""

#: trove/common/utils.py:255
#, python-format
msgid ""
"Time out after waiting %(time)s seconds when running proc: %(args)s "
"%(kwargs)s."
msgstr ""

#: trove/common/wsgi.py:144
msgid "version not supported"
msgstr ""

#: trove/common/wsgi.py:303
msgid "Unserializable result detected."
msgstr ""

#: trove/common/wsgi.py:533
msgid "Invalid service catalog json."
msgstr ""

#: trove/common/wsgi.py:578
#, python-format
msgid "Caught error: %s."
msgstr ""

#: trove/common/rpc/service.py:81
msgid "Failed to stop RPC server before shutdown. "
msgstr ""

#: trove/common/strategies/cluster/experimental/cassandra/taskmanager.py:101
#: trove/common/strategies/cluster/experimental/galera_common/taskmanager.py:135
#: trove/common/strategies/cluster/experimental/redis/taskmanager.py:88
#: trove/common/strategies/cluster/experimental/vertica/taskmanager.py:95
msgid "Error creating cluster."
msgstr ""

#: trove/common/strategies/cluster/experimental/cassandra/taskmanager.py:111
#: trove/common/strategies/cluster/experimental/galera_common/taskmanager.py:145
#: trove/common/strategies/cluster/experimental/redis/taskmanager.py:98
#: trove/common/strategies/cluster/experimental/vertica/taskmanager.py:105
msgid "Timeout for building cluster."
msgstr ""

#: trove/common/strategies/cluster/experimental/cassandra/taskmanager.py:247
#, python-format
msgid "Node did not complete cleanup successfully: %s"
msgstr ""

#: trove/common/strategies/cluster/experimental/cassandra/taskmanager.py:252
msgid "Error growing cluster."
msgstr ""

#: trove/common/strategies/cluster/experimental/cassandra/taskmanager.py:262
#: trove/common/strategies/cluster/experimental/galera_common/taskmanager.py:246
#: trove/common/strategies/cluster/experimental/redis/taskmanager.py:144
#: trove/common/strategies/cluster/experimental/vertica/taskmanager.py:165
msgid "Timeout for growing cluster."
msgstr ""

#: trove/common/strategies/cluster/experimental/cassandra/taskmanager.py:332
msgid "Error shrinking cluster."
msgstr ""

#: trove/common/strategies/cluster/experimental/cassandra/taskmanager.py:342
#: trove/common/strategies/cluster/experimental/galera_common/taskmanager.py:317
#: trove/common/strategies/cluster/experimental/vertica/taskmanager.py:215
msgid "Timeout for shrinking cluster."
msgstr ""

#: trove/common/strategies/cluster/experimental/galera_common/taskmanager.py:148
#, python-format
msgid "Error creating cluster %s."
msgstr ""

#: trove/common/strategies/cluster/experimental/galera_common/taskmanager.py:250
#: trove/common/strategies/cluster/experimental/redis/taskmanager.py:147
#: trove/common/strategies/cluster/experimental/vertica/taskmanager.py:168
#, python-format
msgid "Error growing cluster %s."
msgstr ""

#: trove/common/strategies/cluster/experimental/galera_common/taskmanager.py:278
#, python-format
msgid "Deleting instances (%s)"
msgstr ""

#: trove/common/strategies/cluster/experimental/galera_common/taskmanager.py:283
#: trove/common/strategies/cluster/experimental/mongodb/taskmanager.py:271
#: trove/taskmanager/models.py:306
msgid "timeout for instances to be marked as deleted."
msgstr ""

#: trove/common/strategies/cluster/experimental/galera_common/taskmanager.py:321
#, python-format
msgid "Error shrinking cluster %s."
msgstr ""

#: trove/common/strategies/cluster/experimental/mongodb/api.py:186
#, python-format
msgid ""
"An instance with the options %(given)s is missing the MongoDB required "
"option %(expected)s."
msgstr ""

#: trove/common/strategies/cluster/experimental/mongodb/api.py:193
#, python-format
msgid ""
"The value %(value)s for key %(key)s is invalid. Allowed values are "
"%(valid)s."
msgstr ""

#: trove/common/strategies/cluster/experimental/mongodb/api.py:212
#, python-format
msgid "The arguments %s are not supported by MongoDB."
msgstr ""

#: trove/common/strategies/cluster/experimental/mongodb/api.py:252
msgid ""
"This action cannot be performed on the cluster as no reference shard "
"exists."
msgstr ""

#: trove/common/strategies/cluster/experimental/mongodb/api.py:305
#: trove/common/strategies/cluster/experimental/mongodb/api.py:336
msgid "Not instances specified for grow operation."
msgstr ""

#: trove/common/strategies/cluster/experimental/mongodb/api.py:387
#, python-format
msgid ""
"MongoDB cluster shrink only supports removing an entire shard. Shard "
"%(shard)s has members: %(instances)s"
msgstr ""

#: trove/common/strategies/cluster/experimental/mongodb/api.py:476
#, python-format
msgid "Replica instance does not have required field(s) %s."
msgstr ""

#: trove/common/strategies/cluster/experimental/mongodb/api.py:484
#, python-format
msgid "Instance type %s not supported for MongoDB cluster grow."
msgstr ""

#: trove/common/strategies/cluster/experimental/mongodb/api.py:515
msgid "Duplicate member names not allowed."
msgstr ""

#: trove/common/strategies/cluster/experimental/mongodb/api.py:520
#, python-format
msgid "related_to target(s) %(targets)s do not match any specified names."
msgstr ""

#: trove/common/strategies/cluster/experimental/mongodb/api.py:542
msgid "Members of the same shard have mismatching flavorRef and/or volume values."
msgstr ""

#: trove/common/strategies/cluster/experimental/mongodb/api.py:576
#, python-format
msgid ""
"Shard with instance %s is still active. Please remove the shard from the "
"MongoDB cluster before shrinking."
msgstr ""

#: trove/common/strategies/cluster/experimental/mongodb/taskmanager.py:124
msgid "timeout for building cluster."
msgstr ""

#: trove/common/strategies/cluster/experimental/mongodb/taskmanager.py:171
msgid "timeout for building shard."
msgstr ""

#: trove/common/strategies/cluster/experimental/mongodb/taskmanager.py:247
msgid "timeout for growing cluster."
msgstr ""

#: trove/common/strategies/cluster/experimental/mongodb/taskmanager.py:282
msgid "timeout for shrinking cluster."
msgstr ""

#: trove/common/strategies/cluster/experimental/mongodb/taskmanager.py:309
msgid "error initializing replica set"
msgstr ""

#: trove/common/strategies/cluster/experimental/mongodb/taskmanager.py:330
msgid "error adding shard"
msgstr ""

#: trove/common/strategies/cluster/experimental/mongodb/taskmanager.py:344
msgid "no query routers ready to accept requests"
msgstr ""

#: trove/common/strategies/cluster/experimental/mongodb/taskmanager.py:371
msgid "error adding config servers"
msgstr ""

#: trove/common/strategies/cluster/experimental/vertica/taskmanager.py:198
msgid "Cannot remove master instance!"
msgstr ""

#: trove/common/strategies/cluster/experimental/vertica/taskmanager.py:199
#, python-format
msgid "Marking cluster k-safety: %s"
msgstr ""

#: trove/common/strategies/storage/swift.py:132
#, python-format
msgid ""
"Error saving data segment to swift. ETAG: %(tag)s Segment MD5: "
"%(checksum)s."
msgstr ""

#: trove/common/strategies/storage/swift.py:163
#, python-format
msgid "Error saving data to swift. Manifest ETAG: %(tag)s Swift MD5: %(checksum)s"
msgstr ""

#: trove/common/strategies/storage/swift.py:180
#, python-format
msgid ""
"Original checksum: %(original)s does not match the current checksum: "
"%(current)s"
msgstr ""

#: trove/common/strategies/storage/swift.py:237
#, python-format
msgid "Writing metadata: %s"
msgstr ""

#: trove/conductor/manager.py:49
#, python-format
msgid "[Instance %s] sent field not present. Cannot compare."
msgstr ""

#: trove/conductor/manager.py:81
#, python-format
msgid "[Instance %s] Rec'd message is older than last seen. Discarding."
msgstr ""

#: trove/conductor/manager.py:116
#, python-format
msgid ""
"[Instance: %(instance)s] Backup IDs mismatch! Expected %(expected)s, "
"found %(found)s"
msgstr ""

#: trove/conductor/manager.py:125
#, python-format
msgid ""
"[Instance: %(instance)s] Backup instance IDs mismatch! Expected "
"%(expected)s, found %(found)s"
msgstr ""

#: trove/configuration/models.py:139
#, python-format
msgid "Configuration group with ID %s could not be found."
msgstr ""

#: trove/configuration/service.py:97
#, python-format
msgid ""
"Creating configuration group on tenant %(tenant_id)s with name: "
"%(cfg_name)s"
msgstr ""

#: trove/configuration/service.py:134
#, python-format
msgid "Deleting configuration group %(cfg_id)s on tenant: %(tenant_id)s"
msgstr ""

#: trove/configuration/service.py:153
#, python-format
msgid "Updating configuration group %(cfg_id)s for tenant id %(tenant_id)s"
msgstr ""

#: trove/configuration/service.py:232
msgid "Validating configuration values"
msgstr ""

#: trove/configuration/service.py:243
#, python-format
msgid ""
"Configuration groups are not supported for this datastore: %(name)s "
"%(version)s"
msgstr ""

#: trove/configuration/service.py:254
#, python-format
msgid ""
"The configuration parameter %(key)s is not supported for this datastore: "
"%(name)s %(version)s."
msgstr ""

#: trove/configuration/service.py:267
#, python-format
msgid ""
"The value provided for the configuration parameter %(key)s is not of type"
" %(type)s."
msgstr ""

#: trove/configuration/service.py:277
msgid ""
"Invalid or unsupported min value defined in the configuration-parameters "
"configuration file. Expected integer."
msgstr ""

#: trove/configuration/service.py:283
#, python-format
msgid ""
"The value for the configuration parameter %(key)s is less than the "
"minimum allowed: %(min)s"
msgstr ""

#: trove/configuration/service.py:293
msgid ""
"Invalid or unsupported max value defined in the configuration-parameters "
"configuration file. Expected integer."
msgstr ""

#: trove/configuration/service.py:299
#, python-format
msgid ""
"The value for the configuration parameter %(key)s is greater than the "
"maximum allowed: %(max)s"
msgstr ""

#: trove/configuration/service.py:314
msgid ""
"Invalid or unsupported type defined in the configuration-parameters "
"configuration file."
msgstr ""

#: trove/configuration/service.py:324
#, python-format
msgid "%s is not a supported configuration parameter."
msgstr ""

#: trove/datastore/models.py:219
#, python-format
msgid ""
"Somehow we got a datastore version capability without a parent, that "
"shouldn't happen. %s"
msgstr ""

#: trove/datastore/models.py:262
#, python-format
msgid "Capability Override not found for capability %s"
msgstr ""

#: trove/datastore/models.py:676
msgid "Specify both the datastore and datastore_version_id."
msgstr ""

#: trove/db/models.py:99
#, python-format
msgid "%(s_name)s Not Found"
msgstr ""

#: trove/db/models.py:104
#, python-format
msgid "Tenant %(s_tenant)s tried to access %(s_name)s, owned by %(s_owner)s."
msgstr ""

#: trove/db/models.py:110
#, python-format
msgid "Tenant %(s_tenant)s cannot access %(s_name)s"
msgstr ""

#: trove/db/sqlalchemy/session.py:88
#, python-format
msgid ""
"Configuration option \"query_log\" has been depracated. Use "
"\"connection_debug\" instead. Setting connection_debug = %(debug_level)s "
"instead."
msgstr ""

#: trove/db/sqlalchemy/session.py:106
msgid "***The Database has not been setup!!!***"
msgstr ""

#: trove/dns/models.py:69
#, python-format
msgid "%s Not Found"
msgstr ""

#: trove/extensions/account/service.py:35
#: trove/extensions/account/service.py:46
#: trove/extensions/mgmt/clusters/service.py:44
#: trove/extensions/mgmt/clusters/service.py:75
#: trove/extensions/mgmt/host/service.py:34
#: trove/extensions/mgmt/host/service.py:43
#: trove/extensions/mgmt/volume/service.py:34
#, python-format
msgid ""
"req : '%s'\n"
"\n"
msgstr ""

#: trove/extensions/account/service.py:36
#, python-format
msgid "Showing account information for '%(account)s' to '%(tenant)s'"
msgstr ""

#: trove/extensions/account/service.py:47
#, python-format
msgid "Showing all accounts with instances for '%s'"
msgstr ""

#: trove/extensions/mgmt/clusters/service.py:59
#, python-format
msgid ""
"Showing cluster for tenant '%(tenant_id)s'.\n"
"req : '%(req)s'\n"
"id : '%(id)s'"
msgstr ""

#: trove/extensions/mgmt/clusters/service.py:84
msgid "Invalid cluster action requested."
msgstr ""

#: trove/extensions/mgmt/configuration/service.py:62
msgid "max_size is required for integer data type."
msgstr ""

#: trove/extensions/mgmt/configuration/service.py:65
msgid "min_size is required for integer data type."
msgstr ""

#: trove/extensions/mgmt/configuration/service.py:71
msgid "max_size must be greater than or equal to min_size."
msgstr ""

#: trove/extensions/mgmt/configuration/service.py:77
msgid "Creating configuration parameter for datastore"
msgstr ""

#: trove/extensions/mgmt/configuration/service.py:104
msgid "Updating configuration parameter for datastore"
msgstr ""

#: trove/extensions/mgmt/configuration/service.py:129
msgid "Deleting configuration parameter for datastore"
msgstr ""

#: trove/extensions/mgmt/configuration/service.py:135
#, python-format
msgid "Parameter %s does not exist in the database."
msgstr ""

#: trove/extensions/mgmt/datastores/service.py:51
#, python-format
msgid ""
"Tenant: '%(tenant)s' is adding the datastore version: '%(version)s' to "
"datastore: '%(datastore)s'"
msgstr ""

#: trove/extensions/mgmt/datastores/service.py:66
#, python-format
msgid "Creating datastore %s"
msgstr ""

#: trove/extensions/mgmt/datastores/service.py:109
#, python-format
msgid ""
"Tenant: '%(tenant)s' is updating the datastore version: '%(version)s' for"
" datastore: '%(datastore)s'"
msgstr ""

#: trove/extensions/mgmt/datastores/service.py:147
#, python-format
msgid ""
"Tenant: '%(tenant)s' is removing the datastore version: '%(version)s' for"
" datastore: '%(datastore)s'"
msgstr ""

#: trove/extensions/mgmt/host/models.py:75
#, python-format
msgid "Compute Instance ID found with no associated RD instance: %s."
msgstr ""

#: trove/extensions/mgmt/host/models.py:89
#, python-format
msgid "Unable to update instance: %s."
msgstr ""

#: trove/extensions/mgmt/host/models.py:92
#, python-format
msgid "Failed to update instances: %s."
msgstr ""

#: trove/extensions/mgmt/host/service.py:35
#, python-format
msgid "Indexing a host for tenant '%s'"
msgstr ""

#: trove/extensions/mgmt/host/service.py:44
#, python-format
msgid "Showing a host for tenant '%s'"
msgstr ""

#: trove/extensions/mgmt/host/service.py:45
#, python-format
msgid ""
"id : '%s'\n"
"\n"
msgstr ""

#: trove/extensions/mgmt/host/instance/service.py:31
#, python-format
msgid ""
"Committing an ACTION against host %(host_id)s for tenant '%(tenant_id)s'\n"
"req : '%(req)s'\n"
"\n"
msgstr ""

#: trove/extensions/mgmt/host/instance/service.py:45
#: trove/extensions/mgmt/instances/service.py:113
msgid "Only one action can be specified per request."
msgstr ""

#: trove/extensions/mgmt/host/instance/service.py:49
#, python-format
msgid "Invalid host action: %s"
msgstr ""

#: trove/extensions/mgmt/instances/models.py:41
#, python-format
msgid "Found %d servers in Nova"
msgstr ""

#: trove/extensions/mgmt/instances/models.py:204
#: trove/taskmanager/models.py:100
#, python-format
msgid "Datastore ID for Manager (%s) is not configured"
msgstr ""

#: trove/extensions/mgmt/instances/models.py:263
#, python-format
msgid "Flavor cache miss for %s"
msgstr ""

#: trove/extensions/mgmt/instances/service.py:50
#, python-format
msgid ""
"Indexing a database instance for tenant '%(tenant_id)s'\n"
"req : '%(req)s'\n"
"\n"
msgstr ""

#: trove/extensions/mgmt/instances/service.py:75
#, python-format
msgid ""
"Showing a database instance %(id)s for tenant '%(tenant_id)s'\n"
"req : '%(req)s'\n"
"\n"
msgstr ""

#: trove/extensions/mgmt/instances/service.py:95
#, python-format
msgid ""
"Committing an ACTION against a database instance %(id)s for tenant "
"'%(tenant_id)s'\n"
"req : '%(req)s'\n"
"\n"
msgstr ""

#: trove/extensions/mgmt/instances/service.py:117
#, python-format
msgid "Invalid instance action: %s"
msgstr ""

#: trove/extensions/mgmt/instances/service.py:157
#, python-format
msgid ""
"Showing root history for a database instance %(id)s for tenant "
"'%(tenant_id)s'\n"
"req : '%(req)s'\n"
"\n"
msgstr ""

#: trove/extensions/mgmt/instances/service.py:178
#, python-format
msgid ""
"Showing hardware info for a database instance %(id)s for tenant "
"'%(tenant_id)s'\n"
"req : '%(req)s'\n"
"\n"
msgstr ""

#: trove/extensions/mgmt/instances/service.py:192
#, python-format
msgid ""
"Showing diagnostic info for a database instance %(id)s for tenant "
"'%(tenant_id)s'\n"
"req : '%(req)s'\n"
"\n"
msgstr ""

#: trove/extensions/mgmt/instances/service.py:206
#, python-format
msgid ""
"Sending RPC PING for a database instance %(id)s for tenant "
"'%(tenant_id)s'\n"
"req : '%(req)s'\n"
"\n"
msgstr ""

#: trove/extensions/mgmt/quota/service.py:35
#, python-format
msgid ""
"Indexing quota info for tenant '%(id)s'\n"
"req : '%(req)s'\n"
"\n"
msgstr ""

#: trove/extensions/mgmt/quota/service.py:44
#, python-format
msgid ""
"Updating quota limits for tenant '%(id)s'\n"
"req : '%(req)s'\n"
"\n"
msgstr ""

#: trove/extensions/mgmt/upgrade/service.py:36
#, python-format
msgid ""
"Sending upgrade notifications\n"
"req : '%(req)s'\n"
"Admin tenant_id: %(tenant_id)s"
msgstr ""

#: trove/extensions/mgmt/volume/service.py:35
#, python-format
msgid "Indexing storage info for tenant '%s'"
msgstr ""

#: trove/extensions/mysql/service.py:59
#, python-format
msgid ""
"Listing users for instance '%(id)s'\n"
"req : '%(req)s'\n"
"\n"
msgstr ""

#: trove/extensions/mysql/service.py:71
#, python-format
msgid ""
"Creating users for instance '%(id)s'\n"
"req : '%(req)s'\n"
"\n"
"body: '%(body)s'\n"
"'n"
msgstr ""

#: trove/extensions/mysql/service.py:92
#, python-format
msgid ""
"Delete instance '%(id)s'\n"
"req : '%(req)s'\n"
"\n"
msgstr ""

#: trove/extensions/mysql/service.py:120
#, python-format
msgid ""
"Showing a user for instance '%(id)s'\n"
"req : '%(req)s'\n"
"\n"
msgstr ""

#: trove/extensions/mysql/service.py:138
#, python-format
msgid ""
"Updating user attributes for instance '%(id)s'\n"
"req : '%(req)s'\n"
"\n"
msgstr ""

#: trove/extensions/mysql/service.py:166
#, python-format
msgid ""
"Updating user password for instance '%(id)s'\n"
"req : '%(req)s'\n"
"\n"
msgstr ""

#: trove/extensions/mysql/service.py:220
#, python-format
msgid ""
"Showing user access for instance '%(id)s'\n"
"req : '%(req)s'\n"
"\n"
msgstr ""

#: trove/extensions/mysql/service.py:229 trove/extensions/mysql/service.py:247
#: trove/extensions/mysql/service.py:268
#, python-format
msgid "No such user: %(user)s "
msgstr ""

#: trove/extensions/mysql/service.py:238
#, python-format
msgid ""
"Granting user access for instance '%(id)s'\n"
"req : '%(req)s'\n"
"\n"
msgstr ""

#: trove/extensions/mysql/service.py:259
#, python-format
msgid ""
"Revoking user access for instance '%(id)s'\n"
"req : '%(req)s'\n"
"\n"
msgstr ""

#: trove/extensions/mysql/service.py:287
#, python-format
msgid ""
"Listing schemas for instance '%(id)s'\n"
"req : '%(req)s'\n"
"\n"
msgstr ""

#: trove/extensions/mysql/service.py:300
#, python-format
msgid ""
"Creating schema for instance '%(id)s'\n"
"req : '%(req)s'\n"
"\n"
"body: '%(body)s'\n"
"'n"
msgstr ""

#: trove/extensions/mysql/service.py:319
#, python-format
msgid ""
"Deleting schema for instance '%(id)s'\n"
"req : '%(req)s'\n"
"\n"
msgstr ""

#: trove/extensions/security_group/models.py:70
#: trove/extensions/security_group/models.py:167
msgid "Failed to create remote security group."
msgstr ""

#: trove/extensions/security_group/models.py:77 trove/taskmanager/models.py:754
#, python-format
msgid "Security Group for %s"
msgstr ""

#: trove/extensions/security_group/models.py:115
#: trove/extensions/security_group/models.py:181
msgid "Failed to delete security group."
msgstr ""

#: trove/extensions/security_group/models.py:131
#, python-format
msgid "Security Group with id: %(id)s already had been deleted"
msgstr ""

#: trove/extensions/security_group/models.py:215
msgid "Security Group does not have id defined!"
msgstr ""

#: trove/extensions/security_group/service.py:76
#, python-format
msgid ""
"Attempting to delete Group Rule that does not exist or does not belong to"
" tenant %s"
msgstr ""

#: trove/extensions/security_group/service.py:131
#, python-format
msgid "Create Security Group Rules Required field(s) - %s"
msgstr ""

#: trove/guestagent/api.py:68 trove/guestagent/api.py:71
#: trove/guestagent/api.py:83 trove/guestagent/api.py:86
#, python-format
msgid "Error calling %s"
msgstr ""

#: trove/guestagent/dbaas.py:94
msgid "Error getting volume stats."
msgstr ""

#: trove/guestagent/guest_log.py:178
#, python-format
msgid "Could not retrieve container '%s'"
msgstr ""

#: trove/guestagent/guest_log.py:212
#, python-format
msgid "Not authorized to show log '%s'."
msgstr ""

#: trove/guestagent/guest_log.py:231
#, python-format
msgid "Could not get meta details for log '%s'"
msgstr ""

#: trove/guestagent/guest_log.py:308
#, python-format
msgid "Cannot publish log file '%s' as it does not exist."
msgstr ""

#: trove/guestagent/guest_log.py:313
#, python-format
msgid "Not authorized to publish log '%s'."
msgstr ""

#: trove/guestagent/guest_log.py:321
#, python-format
msgid "Not authorized to discard log '%s'."
msgstr ""

#: trove/guestagent/models.py:87
#, python-format
msgid "Error finding instance %s"
msgstr ""

#: trove/guestagent/pkg.py:122
#, python-format
msgid "Error removing conflict %(package)s"
msgstr ""

#: trove/guestagent/pkg.py:221
#, python-format
msgid "Unexpected output from rpm command. (%(output)s)"
msgstr ""

#: trove/guestagent/pkg.py:244
msgid "Error fixing dpkg"
msgstr ""

#: trove/guestagent/pkg.py:356
msgid "Error updating the apt sources"
msgstr ""

#: trove/guestagent/volume.py:69
msgid "Error getting device status"
msgstr ""

#: trove/guestagent/volume.py:70
#, python-format
msgid "InvalidDevicePath(path=%s)"
msgstr ""

#: trove/guestagent/volume.py:86
msgid "Device path at {0} did not seem to be {1}."
msgstr ""

#: trove/guestagent/volume.py:90
msgid "Volume was not formatted."
msgstr ""

#: trove/guestagent/volume.py:133
msgid "Error resizing file system."
msgstr ""

#: trove/guestagent/volume.py:134
#, python-format
msgid "Error resizing the filesystem: %s"
msgstr ""

#: trove/guestagent/volume.py:147
#, python-format
msgid "Device %(device)s is already mounted in %(mount_point)s. Unmounting now."
msgstr ""

#: trove/guestagent/volume.py:160
msgid "Error retrieving mount points"
msgstr ""

#: trove/guestagent/volume.py:161
#, python-format
msgid "Could not obtain a list of mount points for device: %s"
msgstr ""

#: trove/guestagent/volume.py:172
#, python-format
msgid "Error setting readhead size to %(size)s for device %(device)s."
msgstr ""

#: trove/guestagent/volume.py:175
#, python-format
msgid "Error setting readhead size: %s."
msgstr ""

#: trove/guestagent/backup/backupagent.py:117
#, python-format
msgid "Error saving backup: %(backup_id)s."
msgstr ""

#: trove/guestagent/backup/backupagent.py:121
#, python-format
msgid "Completed backup %(backup_id)s."
msgstr ""

#: trove/guestagent/backup/backupagent.py:178
#, python-format
msgid "Error restoring backup %(id)s."
msgstr ""

#: trove/guestagent/common/operating_system.py:67
#, python-format
msgid "File does not exist: %s"
msgstr ""

#: trove/guestagent/common/operating_system.py:153
#, python-format
msgid "Invalid path: %s"
msgstr ""

#: trove/guestagent/common/operating_system.py:375
#: trove/guestagent/common/operating_system.py:795
#, python-format
msgid "Got unknown keyword args: %r"
msgstr ""

#: trove/guestagent/common/operating_system.py:383
#, python-format
msgid "Service control command not available: %s"
msgstr ""

#: trove/guestagent/common/operating_system.py:386
msgid "Candidate service names not specified."
msgstr ""

#: trove/guestagent/common/operating_system.py:479
msgid "Cannot create a blank directory."
msgstr ""

#: trove/guestagent/common/operating_system.py:508
msgid "Cannot change ownership of a blank file or directory."
msgstr ""

#: trove/guestagent/common/operating_system.py:511
msgid "Please specify owner or group, or both."
msgstr ""

#: trove/guestagent/common/operating_system.py:567
msgid "Cannot change mode of a blank file."
msgstr ""

#: trove/guestagent/common/operating_system.py:598
msgid "Missing user."
msgstr ""

#: trove/guestagent/common/operating_system.py:600
msgid "Missing group."
msgstr ""

#: trove/guestagent/common/operating_system.py:633
msgid "No file mode specified."
msgstr ""

#: trove/guestagent/common/operating_system.py:657
msgid "Cannot remove a blank file."
msgstr ""

#: trove/guestagent/common/operating_system.py:681
#: trove/guestagent/common/operating_system.py:718
msgid "Missing source path."
msgstr ""

#: trove/guestagent/common/operating_system.py:683
#: trove/guestagent/common/operating_system.py:720
msgid "Missing destination path."
msgstr ""

#: trove/guestagent/datastore/manager.py:271
#, python-format
msgid "Starting datastore prepare for '%s'."
msgstr ""

#: trove/guestagent/datastore/manager.py:282
msgid "Applying user-specified configuration (called from 'prepare')."
msgstr ""

#: trove/guestagent/datastore/manager.py:287
#, python-format
msgid "An error occurred preparing datastore: %s"
msgstr ""

#: trove/guestagent/datastore/manager.py:291
#, python-format
msgid "Ending datastore prepare for '%s'."
msgstr ""

#: trove/guestagent/datastore/manager.py:298
#, python-format
msgid "Completed setup of '%s' datastore successfully."
msgstr ""

#: trove/guestagent/datastore/manager.py:306
msgid "Applying modules (called from 'prepare')."
msgstr ""

#: trove/guestagent/datastore/manager.py:308
msgid "Module apply completed."
msgstr ""

#: trove/guestagent/datastore/manager.py:310
#, python-format
msgid "An error occurred applying modules: %s"
msgstr ""

#: trove/guestagent/datastore/manager.py:318
msgid "Creating databases (called from 'prepare')."
msgstr ""

#: trove/guestagent/datastore/manager.py:320
msgid "Databases created successfully."
msgstr ""

#: trove/guestagent/datastore/manager.py:322
msgid "Creating users (called from 'prepare')"
msgstr ""

#: trove/guestagent/datastore/manager.py:324
msgid "Users created successfully."
msgstr ""

#: trove/guestagent/datastore/manager.py:326
#, python-format
msgid "An error occurred creating databases/users: %s"
msgstr ""

#: trove/guestagent/datastore/manager.py:334
msgid "Enabling root user (with password)."
msgstr ""

#: trove/guestagent/datastore/manager.py:336
msgid "Root enabled successfully."
msgstr ""

#: trove/guestagent/datastore/manager.py:338
#, python-format
msgid "An error occurred enabling root user: %s"
msgstr ""

#: trove/guestagent/datastore/manager.py:342
#, python-format
msgid "Calling post_prepare for '%s' datastore."
msgstr ""

#: trove/guestagent/datastore/manager.py:348
#, python-format
msgid "Post prepare for '%s' datastore completed."
msgstr ""

#: trove/guestagent/datastore/manager.py:351
#, python-format
msgid "An error occurred in post prepare: %s"
msgstr ""

#: trove/guestagent/datastore/manager.py:388
msgid "No post_prepare work has been defined."
msgstr ""

#: trove/guestagent/datastore/manager.py:451
msgid "Getting list of guest logs."
msgstr ""

#: trove/guestagent/datastore/manager.py:457
#, python-format
msgid "Returning list of logs: %s"
msgstr ""

#: trove/guestagent/datastore/manager.py:468
#, python-format
msgid ""
"Processing guest log '%(log)s' (enable=%(en)s, disable=%(dis)s, "
"publish=%(pub)s, discard=%(disc)s)."
msgstr ""

#: trove/guestagent/datastore/manager.py:501
#, python-format
msgid "Details for log '%(log)s': %(det)s"
msgstr ""

#: trove/guestagent/datastore/manager.py:539
#, python-format
msgid "%(verb)s log '%(log)s' not supported - no configuration manager defined!"
msgstr ""

#: trove/guestagent/datastore/manager.py:620
msgid "Getting list of modules."
msgstr ""

#: trove/guestagent/datastore/manager.py:623
#: trove/guestagent/datastore/manager.py:654
#, python-format
msgid "Returning list of modules: %s"
msgstr ""

#: trove/guestagent/datastore/manager.py:627
msgid "Applying modules."
msgstr ""

#: trove/guestagent/datastore/manager.py:642
#: trove/guestagent/datastore/manager.py:666
msgid "Module name not specified"
msgstr ""

#: trove/guestagent/datastore/manager.py:644
msgid "Module contents not specified"
msgstr ""

#: trove/guestagent/datastore/manager.py:648
#: trove/guestagent/datastore/manager.py:670
#, python-format
msgid "No driver implemented for module type '%s'"
msgstr ""

#: trove/guestagent/datastore/manager.py:658
msgid "Removing module."
msgstr ""

#: trove/guestagent/datastore/manager.py:674
#, python-format
msgid "Deleted module: %s"
msgstr ""

#: trove/guestagent/datastore/service.py:118
#, python-format
msgid "Set final status to %s."
msgstr ""

#: trove/guestagent/datastore/service.py:125
msgid "Ending restart."
msgstr ""

#: trove/guestagent/datastore/service.py:133
#, python-format
msgid "Current database status is '%s'."
msgstr ""

#: trove/guestagent/datastore/service.py:182
msgid ""
"DB server is not installed or is in restart mode, so for now we'll skip "
"determining the status of DB on this instance."
msgstr ""

#: trove/guestagent/datastore/service.py:212
msgid "Database restart failed."
msgstr ""

#: trove/guestagent/datastore/service.py:239
msgid "Starting database service."
msgstr ""

#: trove/guestagent/datastore/service.py:245
msgid "Enable service auto-start on boot."
msgstr ""

#: trove/guestagent/datastore/service.py:262
msgid "Database failed to start."
msgstr ""

#: trove/guestagent/datastore/service.py:264
msgid "Database has started successfully."
msgstr ""

#: trove/guestagent/datastore/service.py:286
msgid "Stopping database service."
msgstr ""

#: trove/guestagent/datastore/service.py:292
msgid "Database failed to stop."
msgstr ""

#: trove/guestagent/datastore/service.py:294
msgid "Database has stopped successfully."
msgstr ""

#: trove/guestagent/datastore/service.py:297
msgid "Disable service auto-start on boot."
msgstr ""

#: trove/guestagent/datastore/service.py:316
#, python-format
msgid ""
"Service status did not change to %(status)s within the given timeout: "
"%(timeout)ds"
msgstr ""

#: trove/guestagent/datastore/service.py:365
#, python-format
msgid ""
"Timeout while waiting for database status to change.Expected state "
"%(status)s, current state is %(actual_status)s"
msgstr ""

#: trove/guestagent/datastore/experimental/cassandra/manager.py:212
#: trove/guestagent/datastore/experimental/db2/manager.py:123
#: trove/guestagent/datastore/experimental/mongodb/manager.py:185
#: trove/guestagent/datastore/experimental/redis/manager.py:53
#: trove/guestagent/datastore/mysql_common/manager.py:188
#, python-format
msgid "Restoring database from backup %s."
msgstr ""

#: trove/guestagent/datastore/experimental/cassandra/manager.py:218
#: trove/guestagent/datastore/experimental/db2/manager.py:127
#: trove/guestagent/datastore/experimental/mongodb/manager.py:189
#: trove/guestagent/datastore/experimental/redis/manager.py:57
#: trove/guestagent/datastore/mysql_common/manager.py:192
#, python-format
msgid "Error performing restore from backup %s."
msgstr ""

#: trove/guestagent/datastore/experimental/cassandra/manager.py:222
#: trove/guestagent/datastore/experimental/db2/manager.py:131
#: trove/guestagent/datastore/experimental/mongodb/manager.py:193
#: trove/guestagent/datastore/experimental/redis/manager.py:61
#: trove/guestagent/datastore/mysql_common/manager.py:196
msgid "Restored database successfully."
msgstr ""

#: trove/guestagent/datastore/experimental/cassandra/service.py:140
msgid "Preparing Guest as a Cassandra Server"
msgstr ""

#: trove/guestagent/datastore/experimental/cassandra/service.py:149
msgid "Error while initiating storage structure."
msgstr ""

#: trove/guestagent/datastore/experimental/cassandra/service.py:186
msgid "Cannot remove system tables. The service is still running."
msgstr ""

#: trove/guestagent/datastore/experimental/cassandra/service.py:189
msgid "Removing existing system tables."
msgstr ""

#: trove/guestagent/datastore/experimental/cassandra/service.py:247
msgid "Cannot reset the cluster name. The service is still running."
msgstr ""

#: trove/guestagent/datastore/experimental/cassandra/service.py:276
msgid "Configuring Trove superuser."
msgstr ""

#: trove/guestagent/datastore/experimental/cassandra/service.py:325
msgid "Cannot reset the administrative password. The service is still running."
msgstr ""

#: trove/guestagent/datastore/experimental/cassandra/service.py:378
msgid "Cannot change the cluster name. The service is not running."
msgstr ""

#: trove/guestagent/datastore/experimental/cassandra/service.py:423
#, python-format
msgid ""
"Trove administrative user has not been configured yet. Using the built-in"
" default: %s"
msgstr ""

#: trove/guestagent/datastore/experimental/cassandra/service.py:540
msgid "Saving Cassandra cluster topology configuration."
msgstr ""

#: trove/guestagent/datastore/experimental/cassandra/service.py:557
#: trove/guestagent/datastore/experimental/postgresql/service/config.py:110
msgid "The service is still running."
msgstr ""

#: trove/guestagent/datastore/experimental/cassandra/service.py:644
msgid "The node failed to complete its cleanup."
msgstr ""

#: trove/guestagent/datastore/experimental/cassandra/service.py:664
msgid "The node failed to decommission itself."
msgstr ""

#: trove/guestagent/datastore/experimental/cassandra/service.py:728
msgid "Error getting Cassandra status."
msgstr ""

#: trove/guestagent/datastore/experimental/cassandra/service.py:1013
msgid "Updating username requires specifying a password as well."
msgstr ""

#: trove/guestagent/datastore/experimental/cassandra/service.py:1121
#, python-format
msgid "This keyspace-name is reserved: %s"
msgstr ""

#: trove/guestagent/datastore/experimental/cassandra/service.py:1135
#, python-format
msgid "This user-name is reserved: %s"
msgstr ""

#: trove/guestagent/datastore/experimental/cassandra/service.py:1191
msgid "Query execution timed out."
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/manager.py:107
#: trove/guestagent/datastore/experimental/couchdb/manager.py:95
#, python-format
msgid "Restoring database from backup %s"
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/manager.py:112
#: trove/guestagent/datastore/experimental/couchdb/manager.py:100
#, python-format
msgid "Error performing restore from backup %s"
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/manager.py:117
#: trove/guestagent/datastore/experimental/couchdb/manager.py:104
msgid "Restored database successfully"
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/service.py:63
msgid "Preparing Guest as Couchbase Server."
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/service.py:72
msgid "Couchbase Server change data dir path."
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/service.py:91
msgid "Couchbase Server initial setup finished."
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/service.py:93
msgid "Error performing initial Couchbase setup."
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/service.py:127
#, python-format
msgid ""
"Starting Couchbase with configuration changes.\n"
"Configuration contents:\n"
" %s."
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/service.py:130
#, python-format
msgid "Cannot start Couchbase with configuration changes. Couchbase state == %s."
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/service.py:161
msgid "Error getting the Couchbase status."
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/service.py:167
msgid "Error getting the root password from the native Couchbase config file."
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/service.py:181
msgid ""
"Error getting Couchbase status using the password parsed from the native "
"Couchbase config file."
msgstr ""

#: trove/guestagent/datastore/experimental/couchbase/service.py:253
#, python-format
msgid "An error occurred in saving password (%(errno)s). %(strerror)s."
msgstr ""

#: trove/guestagent/datastore/experimental/couchdb/service.py:67
msgid "Preparing guest as a CouchDB server."
msgstr ""

#: trove/guestagent/datastore/experimental/couchdb/service.py:71
msgid "Finished installing CouchDB server."
msgstr ""

#: trove/guestagent/datastore/experimental/couchdb/service.py:91
msgid "Error changing permissions."
msgstr ""

#: trove/guestagent/datastore/experimental/couchdb/service.py:116
msgid "Error while trying to update bind address of CouchDB server."
msgstr ""

#: trove/guestagent/datastore/experimental/couchdb/service.py:127
msgid "Starting CouchDB with configuration changes."
msgstr ""

#: trove/guestagent/datastore/experimental/couchdb/service.py:189
msgid "Error getting CouchDB status."
msgstr ""

#: trove/guestagent/datastore/experimental/couchdb/service.py:234
#: trove/guestagent/datastore/experimental/db2/service.py:269
#, python-format
msgid "Error creating user: %s."
msgstr ""

#: trove/guestagent/datastore/experimental/couchdb/service.py:256
#: trove/guestagent/datastore/experimental/db2/service.py:287
#, python-format
msgid "An error occurred creating users: %s."
msgstr ""

#: trove/guestagent/datastore/experimental/couchdb/service.py:322
#: trove/guestagent/datastore/experimental/db2/service.py:323
#, python-format
msgid "There was an error while deleting user: %s."
msgstr ""

#: trove/guestagent/datastore/experimental/couchdb/service.py:324
#: trove/guestagent/datastore/experimental/db2/service.py:325
#, python-format
msgid "Unable to delete user: %s."
msgstr ""

#: trove/guestagent/datastore/experimental/couchdb/service.py:413
#, python-format
msgid "Cannot grant access for non-existant user: %(user)s"
msgstr ""

#: trove/guestagent/datastore/experimental/couchdb/service.py:420
#, python-format
msgid "Cannot grant access for reserved user %(user)s"
msgstr ""

#: trove/guestagent/datastore/experimental/couchdb/service.py:423
#: trove/guestagent/datastore/experimental/mongodb/service.py:656
#, python-format
msgid "Cannot grant access for reserved or non-existant user %(user)s"
msgstr ""

#: trove/guestagent/datastore/experimental/couchdb/service.py:510
#: trove/guestagent/datastore/experimental/db2/service.py:186
#, python-format
msgid "There was an error creating database: %s."
msgstr ""

#: trove/guestagent/datastore/experimental/couchdb/service.py:515
#: trove/guestagent/datastore/experimental/db2/service.py:191
#, python-format
msgid "Creating the following databases failed: %s."
msgstr ""

#: trove/guestagent/datastore/experimental/couchdb/service.py:555
#: trove/guestagent/datastore/experimental/db2/service.py:204
#, python-format
msgid "There was an error while deleting database:%s."
msgstr ""

#: trove/guestagent/datastore/experimental/couchdb/service.py:557
#: trove/guestagent/datastore/experimental/db2/service.py:206
#, python-format
msgid "Unable to delete database: %s."
msgstr ""

#: trove/guestagent/datastore/experimental/db2/service.py:57
msgid "Command to update the hostname failed."
msgstr ""

#: trove/guestagent/datastore/experimental/db2/service.py:74
msgid "Command to change ownership of  DB2 data directory failed."
msgstr ""

#: trove/guestagent/datastore/experimental/db2/service.py:82
msgid "Command to enable DB2 server on boot failed."
msgstr ""

#: trove/guestagent/datastore/experimental/db2/service.py:90
msgid "Command to disable DB2 server on boot failed."
msgstr ""

#: trove/guestagent/datastore/experimental/db2/service.py:101
msgid "Starting DB2 with configuration changes."
msgstr ""

#: trove/guestagent/datastore/experimental/db2/service.py:115
msgid "Start of DB2 server instance failed."
msgstr ""

#: trove/guestagent/datastore/experimental/db2/service.py:117
msgid "Could not start DB2."
msgstr ""

#: trove/guestagent/datastore/experimental/db2/service.py:131
#: trove/guestagent/datastore/experimental/db2/service.py:133
msgid "Could not stop DB2."
msgstr ""

#: trove/guestagent/datastore/experimental/db2/service.py:159
msgid "Error getting the DB2 server status."
msgstr ""

#: trove/guestagent/datastore/experimental/db2/service.py:251
#, python-format
msgid "An error occurred listing databases: %s."
msgstr ""

#: trove/guestagent/datastore/experimental/mariadb/service.py:74
#: trove/guestagent/datastore/experimental/percona/service.py:64
#: trove/guestagent/datastore/mysql/service.py:47
#: trove/guestagent/datastore/mysql/service.py:84
msgid "Retrieving latest txn id."
msgstr ""

#: trove/guestagent/datastore/experimental/mariadb/service.py:78
#: trove/guestagent/datastore/experimental/percona/service.py:68
#: trove/guestagent/datastore/mysql/service.py:88
#, python-format
msgid "Waiting on txn '%s'."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:71
msgid "Preparing Guest as MongoDB."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:75
msgid "Finished installing MongoDB server."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:104
msgid "Starting MongoDB with configuration changes."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:109
#: trove/guestagent/datastore/experimental/redis/service.py:197
#: trove/guestagent/datastore/experimental/vertica/service.py:227
msgid "Initiating config."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:165
#, python-format
msgid "Bad cluster configuration; instance type given as %s."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:173
msgid "Configuring instance as a cluster query router."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:197
msgid "Configuring instance as a cluster config server."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:203
msgid "Configuring instance as a cluster member."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:244
msgid "Error clearing storage."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:260
#, python-format
msgid "Setting config servers: %s"
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:389
msgid "Cannot secure the instance. The service is still running."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:456
msgid "Error getting MongoDB status."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:514
msgid "User's password is empty."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:554
#, python-format
msgid "Cannot delete user with reserved name %(user)s"
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:617
#, python-format
msgid ""
"Cannot update attributes for user %(user)s as it either does not exist or"
" is a reserved user."
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:677
#, python-format
msgid "Cannot revoke access for reserved or non-existant user %(user)s"
msgstr ""

#: trove/guestagent/datastore/experimental/mongodb/service.py:694
#, python-format
msgid "Cannot list access for reserved or non-existant user %(user)s"
msgstr ""

#: trove/guestagent/datastore/experimental/postgresql/pgutil.py:52
#, python-format
msgid "Invalid SQL statement: %s"
msgstr ""

#: trove/guestagent/datastore/experimental/postgresql/service/access.py:38
msgid "{guest_id}: Granting user ({user}) access to database ({database})."
msgstr ""

#: trove/guestagent/datastore/experimental/postgresql/service/access.py:60
msgid "{guest_id}: Revoking user ({user}) access to database({database})."
msgstr ""

#: trove/guestagent/datastore/experimental/postgresql/service/database.py:50
msgid "{guest_id}: Creating database {name}."
msgstr ""

#: trove/guestagent/datastore/experimental/postgresql/service/database.py:73
msgid "{guest_id}: Dropping database {name}."
msgstr ""

#: trove/guestagent/datastore/experimental/postgresql/service/install.py:53
msgid "{guest_id}: Installing ({packages})."
msgstr ""

#: trove/guestagent/datastore/experimental/postgresql/service/status.py:45
msgid "Error getting Postgres status."
msgstr ""

#: trove/guestagent/datastore/experimental/postgresql/service/users.py:76
msgid "{guest_id}: Creating user {user} {with_clause}."
msgstr ""

#: trove/guestagent/datastore/experimental/postgresql/service/users.py:167
msgid "{guest_id}: Dropping user {name}."
msgstr ""

#: trove/guestagent/datastore/experimental/postgresql/service/users.py:223
msgid "{guest_id}: Altering user {user} {with_clause}."
msgstr ""

#: trove/guestagent/datastore/experimental/postgresql/service/users.py:268
msgid "{guest_id}: Changing username for {old} to {new}."
msgstr ""

#: trove/guestagent/datastore/experimental/postgresql/service/users.py:284
msgid "{guest_id}: Regranting permissions from {old} to {new}."
msgstr ""

#: trove/guestagent/datastore/experimental/pxc/service.py:56
#: trove/guestagent/datastore/mysql_common/service.py:682
msgid "Generating admin password."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/manager.py:78
msgid "Writing redis configuration."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/manager.py:223
msgid "Retrieving latest repl offset."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/manager.py:227
#, python-format
msgid "Waiting on repl offset '%s'."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/manager.py:237
#, python-format
msgid "Timeout occurred waiting for Redis repl offset to change to '%s'."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:64
msgid "Error getting Redis status."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:117
msgid "Preparing Guest as Redis Server."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:119
msgid "Installing Redis."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:121
msgid "Redis installed completely."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:192
msgid "Starting redis with conf changes."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:336
#, python-format
msgid "Error joining node to cluster at %s."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:349
#, python-format
msgid "Error executing addslots: %s"
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:353
#, python-format
msgid "Error adding slots %(first_slot)s-%(last_slot)s to cluster."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:364
msgid "Error getting node info."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:371
msgid "Unable to determine node details"
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:386
msgid "Error validating node to for removal."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:395
msgid "Error removing node from cluster."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:437
#, python-format
msgid "Timeout occurred waiting for Redis persist (%s) to complete."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:444
#, python-format
msgid "Could not persist Redis data (%s)"
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:456
#, python-format
msgid "Could not set configuration property '%(name)s' to '%(value)s'."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:473
#, python-format
msgid "Redis command '%(cmd_name)s %(cmd_args)s' failed."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:487
#, python-format
msgid "Output from Redis command: %s"
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:488
#, python-format
msgid "Field %(field)s not found (Section: '%(sec)s')."
msgstr ""

#: trove/guestagent/datastore/experimental/redis/service.py:496
#, python-format
msgid ""
"Timeout occurred waiting for Redis field '%(field)s' to change to "
"'%(val)s'."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/manager.py:73
#, python-format
msgid "Bad cluster configuration: instance type given as %s."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/manager.py:118
#: trove/guestagent/datastore/galera_common/manager.py:59
msgid "Cluster installation failed."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/manager.py:140
msgid "Cluster grow failed."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/manager.py:150
msgid "Cluster shrink failed."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/manager.py:159
msgid "K-safety setting failed."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:59
msgid "Service Status is RUNNING."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:62
msgid "Service Status is SHUTDOWN."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:65
#: trove/guestagent/datastore/mysql_common/service.py:151
msgid "Failed to get database status."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:119
#, python-format
msgid "Failed to remove config %s"
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:122
#: trove/guestagent/datastore/experimental/vertica/service.py:123
msgid "Vertica configuration remove failed."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:124
msgid "Vertica configuration reset completed."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:137
#, python-format
msgid "Failed to apply config %s"
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:140
#: trove/guestagent/datastore/experimental/vertica/service.py:141
msgid "Vertica configuration apply failed"
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:142
msgid "Vertica config apply completed."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:153
msgid "Failed to enable db on boot."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:163
msgid "Failed to disable db on boot."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:168
msgid "Stopping Vertica."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:187
msgid "Could not stop Vertica."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:194
msgid "Failed to stop database."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:199
msgid "Starting Vertica."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:215
#, python-format
msgid "Could not start Vertica due to %s"
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:222
msgid "Starting Vertica with configuration changes."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:242
msgid "Calling admintools to add DB to host"
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:253
#: trove/guestagent/datastore/experimental/vertica/service.py:270
msgid "adminTools failed as expected - wait for node"
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:255
msgid "Vertica add db to host completed."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:259
msgid "Removing db from node"
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:275
msgid "Vertica remove host from db completed."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:279
msgid "Creating database on Vertica host."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:288
#: trove/guestagent/datastore/experimental/vertica/service.py:289
msgid "Vertica database create failed."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:290
msgid "Vertica database create completed."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:294
msgid "Installing Vertica Server."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:301
#: trove/guestagent/datastore/experimental/vertica/service.py:302
msgid "install_vertica failed."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:304
msgid "install_vertica completed."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:307
#, python-format
msgid "Calling update_vertica with command %s"
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:313
#: trove/guestagent/datastore/experimental/vertica/service.py:314
msgid "update_vertica failed."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:316
msgid "update_vertica completed."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:320
msgid "Adding configured user defined load libraries."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:341
#, python-format
msgid "Failed to create library %s."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:353
#, python-format
msgid "Failed to create source %s."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:359
#, python-format
msgid "The following UDL functions are available for use: %s"
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:395
#, python-format
msgid "Failed to read config %s."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:404
msgid "Preparing Guest as Vertica Server."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:427
msgid "Failed to prepare for install_vertica."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:432
#, python-format
msgid "Setting Vertica k-safety to %s"
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:439
#, python-format
msgid "Failed to set k-safety level %s."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:443
msgid "Creating user in Vertica database."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:452
#, python-format
msgid "Failed to create user %s."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:466
#, python-format
msgid "Failed to grant role %(r)s to user %(u)s."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:495
#: trove/guestagent/datastore/experimental/vertica/service.py:498
#: trove/guestagent/datastore/experimental/vertica/service.py:499
#, python-format
msgid "Failed to update %s password."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:512
#: trove/guestagent/datastore/experimental/vertica/service.py:514
#: trove/guestagent/datastore/experimental/vertica/service.py:613
msgid "Failed to query for root user."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:533
msgid "Cannot read public key."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:560
msgid "Cannot install public keys."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:573
msgid "Cannot export configuration."
msgstr ""

#: trove/guestagent/datastore/experimental/vertica/service.py:621
#, python-format
msgid "Timed out waiting for cluster tochange to status %s"
msgstr ""

#: trove/guestagent/datastore/galera_common/service.py:55
#: trove/guestagent/datastore/mysql_common/service.py:868
msgid "Granting Replication Slave privilege."
msgstr ""

#: trove/guestagent/datastore/galera_common/service.py:65
msgid "Bootstraping cluster."
msgstr ""

#: trove/guestagent/datastore/galera_common/service.py:71
msgid "Error bootstrapping cluster."
msgstr ""

#: trove/guestagent/datastore/galera_common/service.py:72
msgid "Service is not discovered."
msgstr ""

#: trove/guestagent/datastore/galera_common/service.py:80
msgid "Installing cluster configuration."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:94
msgid "/root/.mysql_secret does not exist."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:104
msgid "Cannot change mysql password."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:148
msgid "MySQL Service Status is RUNNING."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:158
#, python-format
msgid "MySQL Service Status %(pid)s is BLOCKED."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:162
msgid "Process execution failed."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:167
msgid "MySQL Service Status is CRASHED."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:170
msgid "MySQL Service Status is SHUTDOWN."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:364
msgid "Error Getting user information"
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:365
#, python-format
msgid "Username %(user)s is not valid: %(reason)s"
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:397
msgid "Error granting access"
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:398
#, python-format
msgid "Grant access to %s is not allowed"
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:669
msgid "Preparing Guest as MySQL Server."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:678
msgid "Finished installing MySQL server."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:717
msgid "Preserving root access from restore."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:747
msgid "Error enabling MySQL start on boot."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:755
msgid "Error disabling MySQL start on boot."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:759
msgid "Stopping MySQL."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:766
msgid "Error stopping MySQL."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:771
msgid "Could not stop MySQL."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:813
#, python-format
msgid "Unable to set %(key)s with value %(value)s."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:828
msgid "Wiping ib_logfiles."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:846
msgid "Removing replication configuration file."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:900
msgid "Starting slave replication."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:907
msgid "Stopping slave replication."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:921
msgid "Stopping replication master."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:936
#, python-format
msgid "Replication is now %s."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:939
#, python-format
msgid "Replication is not %(status)s after %(max)d seconds."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:943
msgid "Starting MySQL."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:968
msgid "Start up of MySQL failed."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:974
msgid "Error killing stalled MySQL start command."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:980
msgid "Starting MySQL with conf changes."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:984
#, python-format
msgid "Cannot execute start_db_with_conf_changes because MySQL state == %s."
msgstr ""

#: trove/guestagent/datastore/mysql_common/service.py:987
#: trove/guestagent/datastore/mysql_common/service.py:993
msgid "Resetting configuration."
msgstr ""

#: trove/guestagent/db/models.py:64 trove/guestagent/db/models.py:565
#, python-format
msgid "Bad dictionary. Keys: %(keys)s. Required: %(reqs)s"
msgstr ""

#: trove/guestagent/db/models.py:97
#, python-format
msgid "Schema name '%(name)s' is too long. Max length = %(max_length)d."
msgstr ""

#: trove/guestagent/db/models.py:102
#, python-format
msgid "'%s' is not a valid schema name."
msgstr ""

#: trove/guestagent/db/models.py:140 trove/guestagent/db/models.py:172
#: trove/guestagent/db/models.py:209
#, python-format
msgid "Bad args. name: %(name)s, deserializing %(deser)s."
msgstr ""

#: trove/guestagent/db/models.py:506
#, python-format
msgid "%(val)s not a valid collation for charset %(char)s."
msgstr ""

#: trove/guestagent/db/models.py:512
#, python-format
msgid "'%s' not a valid collation."
msgstr ""

#: trove/guestagent/db/models.py:530
#, python-format
msgid "'%s' not a valid character set."
msgstr ""

#: trove/guestagent/db/models.py:543
#, python-format
msgid "'%s' is not a valid database name."
msgstr ""

#: trove/guestagent/db/models.py:545
#, python-format
msgid "Database name '%s' is too long. Max length = 64."
msgstr ""

#: trove/guestagent/db/models.py:591 trove/guestagent/db/models.py:892
#: trove/guestagent/db/models.py:985
#, python-format
msgid "'%s' is not a valid password."
msgstr ""

#: trove/guestagent/db/models.py:613 trove/guestagent/db/models.py:915
#: trove/guestagent/db/models.py:1008
#, python-format
msgid "'%s' is not a valid hostname."
msgstr ""

#: trove/guestagent/db/models.py:631
#, python-format
msgid "User name '%(name)s' is too long. Max length = %(max_length)d."
msgstr ""

#: trove/guestagent/db/models.py:636 trove/guestagent/db/models.py:881
#: trove/guestagent/db/models.py:971
#, python-format
msgid "'%s' is not a valid user name."
msgstr ""

#: trove/guestagent/db/models.py:692 trove/guestagent/db/models.py:830
#, python-format
msgid "Bad args. name: %(name)s, password %(pass)s, deserializing %(deser)s."
msgstr ""

#: trove/guestagent/db/models.py:732
#, python-format
msgid "MongoDB user's name missing %s."
msgstr ""

#: trove/guestagent/db/models.py:737
msgid "MongoDB user missing database."
msgstr ""

#: trove/guestagent/db/models.py:741
msgid "MongoDB user missing username."
msgstr ""

#: trove/guestagent/db/models.py:785
#, python-format
msgid "MongoDB user name \"%s\" not in <database>.<username> format."
msgstr ""

#: trove/guestagent/db/models.py:805
#, python-format
msgid "Role %s is invalid."
msgstr ""

#: trove/guestagent/db/models.py:973
#, python-format
msgid "User name '%s' is too long. Max length = 16."
msgstr ""

#: trove/guestagent/module/driver_manager.py:33
msgid "Initializing module driver manager."
msgstr ""

#: trove/guestagent/module/driver_manager.py:49
msgid "No module drivers loaded"
msgstr ""

#: trove/guestagent/module/driver_manager.py:56
#, python-format
msgid "Loading Module driver: %s"
msgstr ""

#: trove/guestagent/module/driver_manager.py:58
msgid "Driver 'type' must be lower-case"
msgstr ""

#: trove/guestagent/module/driver_manager.py:65
#, python-format
msgid "Driver '%(type)s' missing attribute: %(attr)s"
msgstr ""

#: trove/guestagent/module/driver_manager.py:70
#, python-format
msgid "Driver '%s' not supported, skipping"
msgstr ""

#: trove/guestagent/module/driver_manager.py:73
#, python-format
msgid "Exception loading module driver: %s"
msgstr ""

#: trove/guestagent/module/driver_manager.py:85
#, python-format
msgid "Loaded module driver: %s"
msgstr ""

#: trove/guestagent/module/driver_manager.py:88
#, python-format
msgid "Found duplicate driver: %s"
msgstr ""

#: trove/guestagent/module/module_manager.py:68
#, python-format
msgid "Could not apply module '%s'"
msgstr ""

#: trove/guestagent/module/module_manager.py:145
#, python-format
msgid "Could not find module result in %s"
msgstr ""

#: trove/guestagent/module/module_manager.py:203
#, python-format
msgid "Module '%s' has not been applied"
msgstr ""

#: trove/guestagent/module/module_manager.py:209
#, python-format
msgid "Could not remove module '%s'"
msgstr ""

#: trove/guestagent/module/drivers/ping_driver.py:64
#, python-format
msgid "Could not extract contents from '%s' - possibly a binary file?"
msgstr ""

#: trove/guestagent/strategies/backup/mysql_impl.py:69
msgid "Innobackupex log file empty."
msgstr ""

#: trove/guestagent/strategies/backup/mysql_impl.py:73
msgid "Innobackupex did not complete successfully."
msgstr ""

#: trove/guestagent/strategies/backup/mysql_impl.py:87
#, python-format
msgid "Metadata for backup: %s."
msgstr ""

#: trove/guestagent/strategies/backup/experimental/cassandra_impl.py:117
msgid "No data found."
msgstr ""

#: trove/guestagent/strategies/backup/experimental/couchbase_impl.py:90
msgid "All buckets are memcached.  Skipping backup."
msgstr ""

#: trove/guestagent/strategies/backup/experimental/db2_impl.py:47
#, python-format
msgid ""
"Need more free space to backup db2 database, estimated %(est_dump_size)s "
"and found %(avail)s bytes free "
msgstr ""

#: trove/guestagent/strategies/backup/experimental/mongo_impl.py:56
#, python-format
msgid ""
"Need more free space to run mongodump, estimated %(est_dump_size)s and "
"found %(avail)s bytes free "
msgstr ""

#: trove/guestagent/strategies/replication/mysql_base.py:79
msgid "Replication user retry count exceeded"
msgstr ""

#: trove/guestagent/strategies/replication/mysql_base.py:132
msgid "Exception enabling guest as replica"
msgstr ""

#: trove/guestagent/strategies/replication/mysql_binlog.py:40
#, python-format
msgid "Unable to determine binlog position (from file %(binlog_file)s)."
msgstr ""

#: trove/guestagent/strategies/replication/mysql_binlog.py:67
#, python-format
msgid "Setting read permissions on %s"
msgstr ""

#: trove/guestagent/strategies/replication/mysql_binlog.py:69
#, python-format
msgid "Reading log position from %s"
msgstr ""

#: trove/guestagent/strategies/restore/mysql_impl.py:67
msgid "MySQL is still running."
msgstr ""

#: trove/guestagent/strategies/restore/mysql_impl.py:92
msgid "Starting MySQL"
msgstr ""

#: trove/guestagent/strategies/restore/mysql_impl.py:94
msgid "Got a timeout launching mysqld_safe"
msgstr ""

#: trove/guestagent/strategies/restore/mysql_impl.py:110
msgid "Root password reset successfully."
msgstr ""

#: trove/guestagent/strategies/restore/mysql_impl.py:215
#, python-format
msgid "Cleaning out restore location: %s."
msgstr ""

#: trove/guestagent/strategies/restore/mysql_impl.py:224
#: trove/guestagent/strategies/restore/mysql_impl.py:281
msgid "Innobackupex prepare finished successfully."
msgstr ""

#: trove/guestagent/strategies/restore/mysql_impl.py:296
#, python-format
msgid "Restoring parent: %(parent_location)s checksum: %(parent_checksum)s."
msgstr ""

#: trove/guestagent/strategies/restore/experimental/couchbase_impl.py:195
msgid "cbrestore failed. Retrying..."
msgstr ""

#: trove/guestagent/strategies/restore/experimental/db2_impl.py:55
#, python-format
msgid "Cleaning out restore location post: %s."
msgstr ""

#: trove/guestagent/strategies/restore/experimental/redis_impl.py:47
#, python-format
msgid "Removing old persistence file: %s."
msgstr ""

#: trove/instance/models.py:575
msgid "Detach replicas before deleting replica source."
msgstr ""

#: trove/instance/models.py:766
#, python-format
msgid "Cannot create a replica of a replica %(id)s."
msgstr ""

#: trove/instance/models.py:782
#, python-format
msgid "Cannot create a replica of %(id)s as that instance could not be found."
msgstr ""

#: trove/instance/models.py:787
#, python-format
msgid ""
"Replica count only valid when creating replicas. Cannot create %(count)d "
"instances."
msgstr ""

#: trove/instance/models.py:928
#, python-format
msgid "The new flavor id must be different than the current flavor id of '%s'."
msgstr ""

#: trove/instance/models.py:960
#, python-format
msgid "The new volume 'size' must be larger than the current volume size of '%s'."
msgstr ""

#: trove/instance/models.py:968
#, python-format
msgid "Instance %s has no volume."
msgstr ""

#: trove/instance/models.py:1003 trove/instance/models.py:1011
#, python-format
msgid "Instance %s is not a replica."
msgstr ""

#: trove/instance/models.py:1028
#, python-format
msgid "Instance %s is not a replica source."
msgstr ""

#: trove/instance/models.py:1034
#, python-format
msgid "Replica Source %s cannot be ejected as it has a current heartbeat"
msgstr ""

#: trove/instance/models.py:1071
#, python-format
msgid ""
"Instance %(instance_id)s is not currently available for an action to be "
"performed (status was %(action_status)s)."
msgstr ""

#: trove/instance/service.py:398
#, python-format
msgid "Processing log for tenant %s"
msgstr ""

#: trove/instance/service.py:409
msgid "Cannot enable and disable log."
msgstr ""

#: trove/module/models.py:176
#, python-format
msgid "Tenant: %s"
msgstr ""

#: trove/module/models.py:178
#, python-format
msgid "Auto: %s"
msgstr ""

#: trove/module/models.py:180
#, python-format
msgid "Visible: %s"
msgstr ""

#: trove/module/models.py:198
msgid "Cannot specify version without datastore"
msgstr ""

#: trove/module/models.py:271
#, python-format
msgid "Module with ID %s could not be found."
msgstr ""

#: trove/module/service.py:53
#, python-format
msgid "Showing module %s"
msgstr ""

#: trove/module/service.py:66
#, python-format
msgid "Creating module '%s'"
msgstr ""

#: trove/module/service.py:89
#, python-format
msgid "Deleting module %s"
msgstr ""

#: trove/module/service.py:97
#, python-format
msgid "Updating module %s"
msgstr ""

#: trove/module/service.py:131
#, python-format
msgid "Getting instances for module %s"
msgstr ""

#: trove/quota/quota.py:317
#, python-format
msgid "Failed to commit reservations %(reservations)s"
msgstr ""

#: trove/quota/quota.py:330
#, python-format
msgid "Failed to roll back reservations %(reservations)s"
msgstr ""

#: trove/taskmanager/manager.py:124
#, python-format
msgid ""
"promote-to-replica-source: Unable to migrate replica %(slave)s from old "
"replica source %(old_master)s to new source %(new_master)s."
msgstr ""

#: trove/taskmanager/manager.py:138
msgid "Exception demoting old replica source"
msgstr ""

#: trove/taskmanager/manager.py:146
#, python-format
msgid ""
"promote-to-replica-source %(id)s: The following replicas may not have "
"been switched: %(replicas)s"
msgstr ""

#: trove/taskmanager/manager.py:185
#, python-format
msgid "Replicas of %s not all replicating from same master"
msgstr ""

#: trove/taskmanager/manager.py:211
#, python-format
msgid ""
"eject-replica-source: Unable to migrate replica %(slave)s from old "
"replica source %(old_master)s to new source %(new_master)s."
msgstr ""

#: trove/taskmanager/manager.py:227
#, python-format
msgid ""
"eject-replica-source %(id)s: The following replicas may not have been "
"switched: %(replicas)s"
msgstr ""

#: trove/taskmanager/manager.py:315
#, python-format
msgid "Could not create replica %(num)d of %(count)d."
msgstr ""

#: trove/taskmanager/manager.py:343
msgid "Cannot create multiple non-replica instances."
msgstr ""

#: trove/taskmanager/models.py:276
#, python-format
msgid "Timed out while waiting for all instances to become %s."
msgstr ""

#: trove/taskmanager/models.py:283
#, python-format
msgid "Some instances failed: %s"
msgstr ""

#: trove/taskmanager/models.py:354
#, python-format
msgid "Created instance %s successfully."
msgstr ""

#: trove/taskmanager/models.py:358
#, python-format
msgid ""
"Failed to create instance %s. Timeout waiting for instance to become "
"active. No usage create-event was sent."
msgstr ""

#: trove/taskmanager/models.py:363
#, python-format
msgid "Failed to send usage create-event for instance %s."
msgstr ""

#: trove/taskmanager/models.py:375
#, python-format
msgid "Creating instance %s."
msgstr ""

#: trove/taskmanager/models.py:387
#, python-format
msgid "Error creating security group for instance: %s"
msgstr ""

#: trove/taskmanager/models.py:459
#, python-format
msgid "Error creating DNS entry for instance: %s"
msgstr ""

#: trove/taskmanager/models.py:470
#, python-format
msgid "Error attaching instance %s as replica."
msgstr ""

#: trove/taskmanager/models.py:511
#, python-format
msgid "Unable to create replication snapshot record for instance: %s"
msgstr ""

#: trove/taskmanager/models.py:545
#, python-format
msgid ""
"Error creating replication snapshot from instance %(source)s for new "
"replica %(replica)s."
msgstr ""

#: trove/taskmanager/models.py:561
#, python-format
msgid ""
"An error occurred while deleting a bad replication snapshot from instance"
" %(source)s."
msgstr ""

#: trove/taskmanager/models.py:582
#, python-format
msgid ""
"Service status: %(status)s\n"
"Service error description: %(desc)s"
msgstr ""

#: trove/taskmanager/models.py:593
#, python-format
msgid ""
"Trove instance status: %(action)s\n"
"Trove instance status description: %(text)s"
msgstr ""

#: trove/taskmanager/models.py:618
#, python-format
msgid "Service not active, status: %s"
msgstr ""

#: trove/taskmanager/models.py:624
#, python-format
msgid "Server not active, status: %s"
msgstr ""

#: trove/taskmanager/models.py:659
#, python-format
msgid "Error creating server and volume for instance %s"
msgstr ""

#: trove/taskmanager/models.py:766
#, python-format
msgid "Error occurred during Heat stack creation for instance %s."
msgstr ""

#: trove/taskmanager/models.py:798
#, python-format
msgid "Failed to create server for instance %s"
msgstr ""

#: trove/taskmanager/models.py:817
#, python-format
msgid "Failed to create volume for instance %s"
msgstr ""

#: trove/taskmanager/models.py:836
#, python-format
msgid ""
"%(message)s\n"
"%(exc)s\n"
"%(trace)s"
msgstr ""

#: trove/taskmanager/models.py:962
#, python-format
msgid ""
"Failed to create DNS entry for instance %(instance)s. Server status was "
"%(status)s)."
msgstr ""

#: trove/taskmanager/models.py:996
#, python-format
msgid ""
"Failed to create security group rules for instance %(instance_id)s: "
"Invalid port format - FromPort = %(from)s, ToPort = %(to)s"
msgstr ""

#: trove/taskmanager/models.py:1054
#, python-format
msgid "Error stopping the datastore before attempting to delete instance id %s."
msgstr ""

#: trove/taskmanager/models.py:1065
#, python-format
msgid "Error during delete compute server %s"
msgstr ""

#: trove/taskmanager/models.py:1074
#, python-format
msgid "Error during dns entry of instance %(id)s: %(ex)s"
msgstr ""

#: trove/taskmanager/models.py:1083
#, python-format
msgid ""
"Server %(server_id)s entered ERROR status when deleting instance "
"%(instance_id)s!"
msgstr ""

#: trove/taskmanager/models.py:1094
#, python-format
msgid ""
"Failed to delete instance %(instance_id)s: Timeout deleting compute "
"server %(server_id)s"
msgstr ""

#: trove/taskmanager/models.py:1104
#, python-format
msgid "Deleting volume %(v)s for instance: %(i)s."
msgstr ""

#: trove/taskmanager/models.py:1108
#, python-format
msgid "Error deleting volume of instance %(id)s."
msgstr ""

#: trove/taskmanager/models.py:1123
#, python-format
msgid ""
"Resizing volume for instance %(instance_id)s from %(old_size)s GB to "
"%(new_size)s GB."
msgstr ""

#: trove/taskmanager/models.py:1129
#, python-format
msgid "Resized volume for instance %s successfully."
msgstr ""

#: trove/taskmanager/models.py:1132
#, python-format
msgid ""
"Resizing instance %(instance_id)s from flavor %(old_flavor)s to "
"%(new_flavor)s."
msgstr ""

#: trove/taskmanager/models.py:1138
#, python-format
msgid "Resized instance %s successfully."
msgstr ""

#: trove/taskmanager/models.py:1141
#, python-format
msgid "Initiating migration to host %s."
msgstr ""

#: trove/taskmanager/models.py:1146
#, python-format
msgid "Initiating backup for instance %s."
msgstr ""

#: trove/taskmanager/models.py:1165
#, python-format
msgid "Failed to get replication snapshot from %s."
msgstr ""

#: trove/taskmanager/models.py:1179
#, python-format
msgid "Failed to detach replica %s."
msgstr ""

#: trove/taskmanager/models.py:1192
#, python-format
msgid "Failed to attach replica %s."
msgstr ""

#: trove/taskmanager/models.py:1271
#, python-format
msgid "Cannot reboot instance. DB status is %s."
msgstr ""

#: trove/taskmanager/models.py:1277
#, python-format
msgid "Rebooting instance %s."
msgstr ""

#: trove/taskmanager/models.py:1294
#, python-format
msgid "Rebooted instance %s successfully."
msgstr ""

#: trove/taskmanager/models.py:1296
#, python-format
msgid "Failed to reboot instance %(id)s: %(e)s"
msgstr ""

#: trove/taskmanager/models.py:1303
#, python-format
msgid "Initiating datastore restart on instance %s."
msgstr ""

#: trove/taskmanager/models.py:1307
#, python-format
msgid "Failed to initiate datastore restart on instance %s."
msgstr ""

#: trove/taskmanager/models.py:1313
#, python-format
msgid "Retrieving guest log list for instance %s."
msgstr ""

#: trove/taskmanager/models.py:1317
#, python-format
msgid "Failed to retrieve guest log list for instance %s."
msgstr ""

#: trove/taskmanager/models.py:1323
#, python-format
msgid "Processing guest log for instance %s."
msgstr ""

#: trove/taskmanager/models.py:1328
#, python-format
msgid "Failed to process guest log for instance %s."
msgstr ""

#: trove/taskmanager/models.py:1398
#, python-format
msgid "Deleting backup %s."
msgstr ""

#: trove/taskmanager/models.py:1411
#, python-format
msgid "Error occurred when deleting from swift. Details: %s"
msgstr ""

#: trove/taskmanager/models.py:1419
#, python-format
msgid "Deleted backup %s successfully."
msgstr ""

#: trove/taskmanager/models.py:1439
#, python-format
msgid ""
"%(func)s encountered an error when attempting to resize the volume for "
"instance %(id)s. Setting service status to failed."
msgstr ""

#: trove/taskmanager/models.py:1449
#, python-format
msgid ""
"%(func)s encountered an error when attempting to resize the volume for "
"instance %(id)s. Trying to recover by restarting the guest."
msgstr ""

#: trove/taskmanager/models.py:1457
#, python-format
msgid ""
"%(func)s encountered an error when attempting to resize the volume for "
"instance %(id)s. Trying to recover by mounting the volume and then "
"restarting the guest."
msgstr ""

#: trove/taskmanager/models.py:1466
#, python-format
msgid ""
"%(func)s encountered an error when attempting to resize the volume for "
"instance %(id)s. Trying to recover by attaching and mounting the volume "
"and then restarting the guest."
msgstr ""

#: trove/taskmanager/models.py:1574
#, python-format
msgid "Failed to get volume %(vol_id)s"
msgstr ""

#: trove/taskmanager/models.py:1588
#, python-format
msgid "Timeout trying to extend the volume %(vol_id)s for instance %(id)s"
msgstr ""

#: trove/taskmanager/models.py:1601
#, python-format
msgid ""
"Error encountered trying to verify extend for the volume %(vol_id)s for "
"instance %(id)s"
msgstr ""

#: trove/taskmanager/models.py:1649
#, python-format
msgid ""
"Failed to resize instance %(id)s volume for server %(server_id)s. The "
"instance must be in state %(state)s not %(inst_state)s."
msgstr ""

#: trove/taskmanager/models.py:1772
msgid "Exception during nova action."
msgstr ""

#: trove/taskmanager/models.py:1774
#, python-format
msgid "Reverting action for instance %s"
msgstr ""

#: trove/taskmanager/models.py:1780
msgid "Restarting datastore."
msgstr ""

#: trove/taskmanager/models.py:1783
msgid "Cannot restart datastore because Nova server status is not ACTIVE"
msgstr ""

#: trove/taskmanager/models.py:1786
#, python-format
msgid "Error resizing instance %s."
msgstr ""

#: trove/taskmanager/models.py:1848
msgid "Error sending reset_configuration call."
msgstr ""

#: trove/tests/db/migrations.py:74
#, python-format
msgid ""
"The following migration scripts are missing a downgrade implementation:\n"
"\t%s"
msgstr ""

#: trove/tests/fakes/nova.py:279
#, python-format
msgid "volume status = %s"
msgstr ""

#: trove/tests/fakes/nova.py:331
#, python-format
msgid "Couldn't find server id %(id)s, collection=%(db)s"
msgstr ""

#: trove/tests/fakes/nova.py:351
#, python-format
msgid "Simulated event ended, deleting server %s."
msgstr ""

#: trove/tests/fakes/nova.py:494
#, python-format
msgid "Couldn't find volume id %(id)s, collection=%(db)s"
msgstr ""

